
package Vistas;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.HashMap;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Lenovo
 */
public class ConsultaDos extends javax.swing.JFrame {

     private final Map<String, Object[][]> datosPorPais;
    /**
     * Creates new form ConsultaDos
     */
    
    public ConsultaDos() {
        initComponents();  // Inicializa los componentes de la interfaz
        personalizarComponentes();
        datosPorPais = cargarDatosPorPais();  // Inicializa los datos por año
        jButton2.addActionListener(e -> {
            llenarTablaConDatosSegunPais();
            mostrarGrafico(); // Llama a mostrarGrafico al presionar calcular
        });
    }
    
     private void personalizarComponentes() {
    Font fuenteBonita = new Font("Sans-Serif", Font.BOLD, 18); // Fuente sans-serif, negrita, tamaño 18
    Font fuenteBonitaDos = new Font("Sans.Serif", Font.BOLD, 13);
    Color colorNegroSuave = new Color(0, 0, 0); 
    
   
    jLabel1.setFont(fuenteBonita); 
    jLabel1.setForeground(colorNegroSuave); 
    
    jLabel2.setFont(fuenteBonitaDos); 
    jLabel2.setForeground(colorNegroSuave);  
        
    }

    private Map<String, Object[][]> cargarDatosPorPais() {
        // Define los datos para cada país
        Map<String, Object[][]> datos = new HashMap<>();

        datos.put("Colombia", new Object[][]{
                {"Colombia", 1543, 4000, 0.0},
        });

        datos.put("Argentina", new Object[][]{
                {"Argentina", 20540000, 500000, 0.0},
        });

        datos.put("Brazil", new Object[][]{
                {"Brazil", 3045000, 1500000, 0.0},
        });

        datos.put("España", new Object[][]{
                {"España", 2504400, 1250000, 0.0},
        });

        datos.put("Puerto Rico", new Object[][]{
                {"Puerto Rico", 4500230, 1650000, 0.0},
        });

        return datos;
    }

    private void llenarTablaConDatosSegunPais() {
    String paisSeleccionado = (String) jComboBox1.getSelectedItem();
    DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
    modelo.setRowCount(0);

    Object[][] datos = datosPorPais.get(paisSeleccionado);
    if (datos != null) {
        for (Object[] fila : datos) {
            String pais = (String) fila[0];
            Number consumo = (Number) fila[1];
            Number produccion = (Number) fila[2];
            // Calcular el porcentaje de energía renovable
            double porcentajeRenovable = (produccion.doubleValue() / consumo.doubleValue()) * 100;

            // Agregar los datos a la tabla
            modelo.addRow(new Object[]{pais, consumo, produccion, porcentajeRenovable});
        }
    }
}

   private void mostrarGrafico() {
    String paisSeleccionado = (String) jComboBox1.getSelectedItem();
    Object[][] datos = datosPorPais.get(paisSeleccionado);
    
    if (datos != null && datos.length > 0) {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for (Object[] fila : datos) {
            String pais = (String) fila[0];
            Number consumo = (Number) fila[1];
            Number produccion = (Number) fila[2];
            dataset.addValue(consumo, "Consumo Total (kWh)", pais);
            dataset.addValue(produccion, "Producción Renovable (kWh)", pais);
        }

        // Crear el gráfico
        JFreeChart chart = ChartFactory.createBarChart(
                "Consumo y Producción de Energía",
                "País",
                "Cantidad (kWh)",
                dataset
        );

        // Crear y agregar el panel del gráfico
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new Dimension(800, 400));

        // Limpiar el panel existente
        jPanel2.removeAll(); 
        jPanel2.setLayout(new BorderLayout()); 
        jPanel2.add(chartPanel, BorderLayout.CENTER); // Agregar el gráfico
        jPanel2.revalidate(); 
        jPanel2.repaint(); // Repaint para actualizar la vista
    } else {
        System.out.println("No hay datos para mostrar el gráfico."); // Mensaje de depuración
    }   
   }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 811, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );

        jButton1.setText("Atras");

        jLabel1.setText("Porcentaje de Energía Renovable en el Consumo Eléctrico Total por Región");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Colombia", "España", "Brazil", "Puerto Rico", "Argentina" }));

        jLabel2.setText("Seleccionar país");

        jButton2.setText("Calcular");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "País", "Consumo Total (kWh)", "Producción Renovable (kWh)", "Porcentaje de Energía Renovable (%)"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1)
                                .addGap(129, 129, 129)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(261, 261, 261)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(jButton2)))
                        .addGap(0, 201, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        jComboBox1.getAccessibleContext().setAccessibleName("");
        jComboBox1.getAccessibleContext().setAccessibleParent(jComboBox1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
        public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaDos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaDos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaDos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaDos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaDos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
