/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Controllers.EnergiaRenovableController;
import Controllers.UsuarioController;
import Model.Rol;
import Model.Usuario;
import Repository.EnergiaRenovableRepository;
import Repository.UsuarioRepository;
import Services.EnergiaRenovableService;
import Services.UsuarioService;

import java.awt.Font;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 * @author MI PC
 */
public class PanelMenuPrincipal extends javax.swing.JFrame {

    private UsuarioController usuarioController;
    private UsuarioService usuarioService;
    private DefaultTableModel tableModel;
    long idUser = 0;

    /**
     * Creates new form PanelMenuPrincipal
     */
    public PanelMenuPrincipal() {
        initComponents();
        usuarioService = new UsuarioService();
        usuarioController = new UsuarioController();
        this.setVisible(true);
        setLocationRelativeTo(null);
        this.setResizable(false);
        inicializarTablaUsuario();
        icicializarComboboxRol(); 
        setFuentes(); 

    }
    private void icicializarComboboxRol(){
        UsuarioRepository usuarioRepository = new UsuarioRepository();

        UsuarioService usuarioService = new UsuarioService(usuarioRepository);

        UsuarioController usuarioController = new UsuarioController(usuarioService);

        List<Rol> listRoles = usuarioController.obtenerListaRol();

         for (Rol rol : listRoles) {
            jComboBoxRol.addItem(rol.getNombre());
        }
        
    }
    private void setFuentes(){
        jTableUsuarios.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 16));
        jTableUsuarios.getTableHeader().setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 16));
        
        jLabelNombre.setFont(new Font(jLabelNombre.getFont().getName(), Font.PLAIN, 16));
        jLabelContrasenia.setFont(new Font(jLabelContrasenia.getFont().getName(), Font.PLAIN, 16));
        jLabelEmail.setFont(new Font(jLabelEmail.getFont().getName(), Font.PLAIN, 16));
        jLabelRol.setFont(new Font(jLabelRol.getFont().getName(), Font.PLAIN, 16));

        jTextNombreUsuario.setFont(new Font(jTextNombreUsuario.getFont().getName(), Font.PLAIN, 16));
        jTextContrasenia.setFont(new Font(jTextContrasenia.getFont().getName(), Font.PLAIN, 16));
        jTextEmail.setFont(new Font(jTextEmail.getFont().getName(), Font.PLAIN, 16));
        jComboBoxRol.setFont(new Font(jComboBoxRol.getFont().getName(), Font.PLAIN, 16));

        jTabbedEnergias.setFont(new Font(jTabbedEnergias.getFont().getName(), Font.PLAIN, 16));
        jTableUsuarios.setFont(new Font(jTableUsuarios.getFont().getName(), Font.PLAIN, 16));

        jButtonGuardar.setFont(new Font(jButtonGuardar.getFont().getName(), Font.PLAIN, 16));
        jButtonBuscar.setFont(new Font(jButtonBuscar.getFont().getName(), Font.PLAIN, 16));
        jButtonEliminar.setFont(new Font(jButtonEliminar.getFont().getName(), Font.PLAIN, 16));
        jButtonActualizar.setFont(new Font(jButtonActualizar.getFont().getName(), Font.PLAIN, 16));
    }

    private void inicializarTablaUsuario() {
        tableModel = (DefaultTableModel) jTableUsuarios.getModel();

        jTableUsuarios.getColumnModel().getColumn(0).setPreferredWidth(20);
        jTableUsuarios.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTableUsuarios.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTableUsuarios.getColumnModel().getColumn(3).setPreferredWidth(100);

        EnergiaRenovableRepository energiaRepository = new EnergiaRenovableRepository();

        EnergiaRenovableService energiaService = new EnergiaRenovableService(energiaRepository);

        EnergiaRenovableController energiaController = new EnergiaRenovableController(energiaService);

         cargarUsuariosEnTabla();
        
        jTableUsuarios.getSelectionModel().addListSelectionListener(event -> {
            if (!event.getValueIsAdjusting() && jTableUsuarios.getSelectedRow() != -1) {
                cargarDatosUsuarioSeleccionado();
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedEnergias = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonBuscar = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jLabelNombre = new javax.swing.JLabel();
        jTextNombreUsuario = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextEmail = new javax.swing.JTextField();
        jLabelContrasenia = new javax.swing.JLabel();
        jTextContrasenia = new javax.swing.JTextField();
        jLabelRol = new javax.swing.JLabel();
        JtablaUsuarios = new javax.swing.JScrollPane();
        jTableUsuarios = new javax.swing.JTable();
        jButtonGuardar = new javax.swing.JButton();
        jComboBoxRol = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 711, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
        );

        jTabbedEnergias.addTab("Gestion de Energias renovables", jPanel1);

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });

        jButtonEliminar.setText("Eliminar");

        jLabelNombre.setText("Nombre");

        jTextNombreUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabelEmail.setText("E-mail");

        jTextEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEmailActionPerformed(evt);
            }
        });

        jLabelContrasenia.setText("Contraseña");

        jLabelRol.setText("Rol");

        JtablaUsuarios.setToolTipText("");

        jTableUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jTableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Email", "Rol"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableUsuarios.setAlignmentX(0.8F);
        jTableUsuarios.setAlignmentY(0.8F);
        jTableUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTableUsuarios.setName(""); // NOI18N
        jTableUsuarios.setRowHeight(25);
        JtablaUsuarios.setViewportView(jTableUsuarios);
        if (jTableUsuarios.getColumnModel().getColumnCount() > 0) {
            jTableUsuarios.getColumnModel().getColumn(0).setResizable(false);
            jTableUsuarios.getColumnModel().getColumn(1).setResizable(false);
            jTableUsuarios.getColumnModel().getColumn(2).setResizable(false);
            jTableUsuarios.getColumnModel().getColumn(3).setResizable(false);
        }
        jTableUsuarios.getAccessibleContext().setAccessibleName("");

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextNombreUsuario)
                    .addComponent(jLabelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextEmail)
                    .addComponent(jLabelContrasenia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextContrasenia)
                    .addComponent(jLabelRol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxRol, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(jButtonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(JtablaUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabelNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabelEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabelContrasenia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelRol, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxRol, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(JtablaUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jTabbedEnergias.addTab("Gestion de usuarios", jPanel2);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedEnergias, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedEnergias))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        actualizarUsuario();
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jTextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEmailActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
         agregarUsuario();
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void cargarUsuariosEnTabla() {
        UsuarioRepository usuarioRepository = new UsuarioRepository();

        UsuarioService usuarioService = new UsuarioService(usuarioRepository);

        UsuarioController usuarioController = new UsuarioController(usuarioService);
        
        List<Usuario> listUsuarios = usuarioController.obtenerUsuarios();

        tableModel.setRowCount(0);
        for (Usuario usuario : listUsuarios) {
            tableModel.addRow(new Object[]{
                usuario.getId(),
                usuario.getNombre(),
                usuario.getEmail(),
                usuario.getRol().getNombre()
            });
        }
    }
    
        private void cargarDatosUsuarioSeleccionado() {
        int filaSeleccionada = jTableUsuarios.getSelectedRow();
        if (filaSeleccionada != -1) {
            idUser = (long) jTableUsuarios.getValueAt(filaSeleccionada, 0);
            String nombre = jTableUsuarios.getValueAt(filaSeleccionada, 1).toString();
            String email = jTableUsuarios.getValueAt(filaSeleccionada, 2).toString();
            String rol = jTableUsuarios.getValueAt(filaSeleccionada, 3).toString();
            jComboBoxRol.setSelectedItem(rol);
            jTextNombreUsuario.setText(nombre);
            jTextEmail.setText(email);
        }
    }
    
    
    private void agregarUsuario() {
        UsuarioRepository usuarioRepository = new UsuarioRepository();

        UsuarioService usuarioService = new UsuarioService(usuarioRepository);

        UsuarioController usuarioController = new UsuarioController(usuarioService);
        String nombre = jTextNombreUsuario.getText().trim();
        String email = jTextEmail.getText().trim();
        String contrasenia = jTextContrasenia.getText().trim();
        String nombreRol = (String) jComboBoxRol.getSelectedItem();

        if (nombre.isEmpty() || email.isEmpty() || contrasenia.isEmpty() || nombreRol.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos por favor", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Rol rol = new Rol(); 
        rol.setNombre(nombreRol);

        Usuario usuario = new Usuario(0, nombre, email, contrasenia, rol); 

        usuarioController.agregarUsuario(usuario);
        cargarUsuariosEnTabla();

        JOptionPane.showMessageDialog(this, "Registro agregado");
        
        
    }
    
    private void actualizarUsuario() {
      // cargarDatosUsuarioSeleccionado();
        UsuarioRepository usuarioRepository = new UsuarioRepository();
        UsuarioService usuarioService = new UsuarioService(usuarioRepository);
        UsuarioController usuarioController = new UsuarioController(usuarioService);
        try {
                    // Obtener datos de los campos
                    String nombre =  jTextNombreUsuario.getText();
                    String email = jTextEmail.getText();
                    String contrasenia = jTextContrasenia.getText().trim();
                    String nombreRol = (String) jComboBoxRol.getSelectedItem();
                    
                    if (nombre.isEmpty() || email.isEmpty() || contrasenia.isEmpty() || nombreRol.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Complete todos los campos por favor", "Input Error", JOptionPane.ERROR_MESSAGE);
                    return;
                     }

                    
                    Rol rol = new Rol(); 
                    rol.setNombre(nombreRol);
                    rol.setId(1);
                    

                    // Crear el objeto Usuario y Rol
                    Usuario usuario = new Usuario(); 
                    usuario.setId(idUser);
                    usuario.setContrasenia(contrasenia);
                    usuario.setNombre(nombre);
                    usuario.setEmail(email);
                    usuario.setRol(rol);
                    

                    
                    // Actualizar el usuario
                   usuarioController.actualizarUsuario(usuario);
                   cargarUsuariosEnTabla();
                 
                    JOptionPane.showMessageDialog(null, "Usuario actualizado correctamente.");
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Error al actualizar usuario: " + ex.getMessage());
                }
        
            }
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelMenuPrincipal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JtablaUsuarios;
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JComboBox<String> jComboBoxRol;
    private javax.swing.JLabel jLabelContrasenia;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelRol;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedEnergias;
    private javax.swing.JTable jTableUsuarios;
    private javax.swing.JTextField jTextContrasenia;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
