package Vistas;

import Controllers.EnergiaRenovableController;
import Controllers.UsuarioController;
import Repository.EnergiaRenovableRepository;
import Repository.UsuarioRepository;
import Services.EnergiaRenovableService;
import Services.UsuarioService;
import java.awt.Color;
import java.awt.Font;

import java.util.ArrayList;
import java.util.List;
import javax.swing.border.LineBorder;


public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        agregarConsultas();
        setLocationRelativeTo(null);
        this.setResizable(false);
    }

    private void agregarConsultas() {
        List<String> consultas = new ArrayList<>();
        consultas.add("Obtener producción total de energía renovable por tipo de fuente en un año específico");
        consultas.add("Otra consulta");
        jLabel6.setForeground(Color.RED);
        jLabel6.setFont(new Font(jLabel6.getFont().getName(), Font.PLAIN, 16));
        jLabel1.setFont(new Font(jLabel1.getFont().getName(), Font.PLAIN, 16));
        jLabel2.setFont(new Font(jLabel2.getFont().getName(), Font.PLAIN, 16));
        jLabel3.setFont(new Font(jLabel3.getFont().getName(), Font.PLAIN, 16));
        jLabel4.setFont(new Font(jLabel4.getFont().getName(), Font.PLAIN, 16));
        //jLabel5.setFont(new Font(jLabel5.getFont().getName(), Font.PLAIN, 16));

        jTextField1.setFont(new Font(jTextField1.getFont().getName(), Font.PLAIN, 16));
        jTextField2.setFont(new Font(jTextField2.getFont().getName(), Font.PLAIN, 16));

        jTextField1.setBorder(new LineBorder(Color.GRAY, 2, true));
        jTextField2.setBorder(new LineBorder(Color.GRAY, 2, true));

        jButton1.setFont(new Font(jButton1.getFont().getName(), Font.PLAIN, 16));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1.setBackground(Color.GRAY);
                jButton1.setForeground(Color.WHITE);
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1.setBackground(Color.LIGHT_GRAY);
                jButton1.setForeground(Color.BLACK);
            }
        });

        // Agregar elementos al JComboBox
        /*
        for (String consulta : consultas) {
            jComboBox1.addItem(consulta);
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Transicion de Energias Renovables");

        jLabel2.setText("Login");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Email");

        jLabel4.setText("Contraseña");

        jLabel6.setText("*");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField1)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(358, 358, 358)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(278, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addComponent(jLabel2)
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addContainerGap(216, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

 /*String selectedItem = (String) jComboBox1.getSelectedItem();
        System.out.println("Seleccionaste: " + selectedItem);
        if(selectedItem == "Obtener producción total de energía renovable por tipo de fuente en un año específico"){
             ConsultaUno consultaUno = new ConsultaUno();
            System.out.println("Seleccionaste: " + selectedItem);
              this.setVisible(false);
        }
        */


        EnergiaRenovableRepository energiaRepository = new EnergiaRenovableRepository();

        EnergiaRenovableService energiaService = new EnergiaRenovableService(energiaRepository);

        EnergiaRenovableController controller = new EnergiaRenovableController(energiaService);
        
        UsuarioRepository usuarioRepository = new UsuarioRepository();
        
        UsuarioService usuarioService = new UsuarioService(usuarioRepository);

        UsuarioController usuarioController = new UsuarioController(usuarioService);

        String email = jTextField1.getText();
        String contrasenia = jTextField2.getText();

        boolean ingreso = usuarioController.iniciarSesion(email, contrasenia);
        if (ingreso) {
            /*
            ConsultaUno consultaUno = new ConsultaUno();
            this.setVisible(false);
            */
            PanelMenuPrincipal panelMenuPrincipal = new PanelMenuPrincipal();
            this.setVisible(false);
        } else {
            jLabel6.setText("El usuario o la contraseña son incorrectos");
            System.out.println("No funciona................");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}